name: deploy hello world python app

on:
    push:
        branches: [main, python-app, feature/goodbye]
        path :
            - 'first-app/**'
            - '.github/workflows/calling-template-helloworld-py.yml'
            - '.github/workflows/webapp-template.yml'
    workflow_dispatch:
        inputs:
            name:
                type: string
                description: what is your name
            app-type:
                tpye: choice
                description: what is your application language
                options:
                - python
                - angular
jobs:
    deploy:
        uses: ./.github/workflows/webapp-template.yml
        with:
            python-version: '3.13'
            app-path: 'first-app'
            webapp-name: 'python-first-app'
            calling-branch: ${{ github.ref_name }}
        secrets:
            publish-profile: ${{ secrets.PYTHON_PUBLISH_PROFILE }}
