name: reuseable webapp-template-python

on:
  workflow_call:
    inputs:
        python-version:
            description: 'Python version to use'
            type: string
            required: true
            default: '3.10'
        app-path:
            description: 'Path to the application files'
            type: string
            required: true
            default: '.'
        webapp-name:
            description: 'webapp name to publish into'
            type: string
            required: true
            default: 'pytest'
        calling-branch:
            description: 'Branch that is calling this workflow'
            type: string
            required: false
            default: 'main'
    secrets:
        publish-profile:
            description: 'Azure publish profile secret'
            required: true
jobs:
    webapp-template:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ inputs.python-version }}

        - name: Set up env var for branch
          run: echo "calling_branch=${{ inputs.calling-branch }}" >> $GITHUB_ENV

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r ${{ inputs.app-path }}/requirements.txt
    
        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ inputs.webapp-name }}
            publish-profile: ${{ secrets.publish-profile }}
            package: ${{ inputs.app-path }}
